- name: Install MariaDB Server
  apt:
    pkg:
      - mariadb-server
  become: yes
  tags: mariadb

- name: Start and enable MariaDB Server
  service:
    name: mariadb
    state: started
    enabled: yes
  become: yes
  tags: mariadb

- name: Install pip3
  apt:
    name: python3-pip
  become: yes
  tags: mariadb

- name: Install PyMySQL
  pip:
    name: PyMySQL
  become: yes
  tags: mariadb

- name: Create database
  mysql_db:
    db: "{{ dbname }}"
    state: present
    encoding: utf8
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes
  tags: mariadb

- name: Create database user
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ dbpass }}"
    priv: "{{ dbname }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes
  tags: mariadb
