- name: Include vars of PHP
  include_vars:
    file: php.yml
    name: php
  tags: wordpress

- name: Add ondrej/php PPA repository
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: yes
  become: yes
  tags: php

- name: Install PHP
  apt:
    pkg:
      - "php{{ php.version }}"
      - "php{{ php.version }}-fpm"
  become: yes
  tags: php
