- name: Add ondrej/php PPA repository
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: yes
  become: yes
  tags: php

- name: Install PHP 8.2
  apt:
    pkg:
      - php8.2
      - php8.2-fpm
  become: yes
  tags: php
