- name: Include vars of WordPress
  include_vars:
    file: wordpress.yml
    name: wordpress
  tags: wordpress

- name: Include vars of MariaDB
  include_vars:
    file: mariadb.yml
    name: mariadb
  tags: wordpress

- name: Include vars of PHP
  include_vars:
    file: php.yml
    name: php
  tags: wordpress

- name: Download WordPress package
  get_url:
    url: "https://ja.wordpress.org/wordpress-{{ wordpress.version }}-ja.tar.gz"
    dest: /tmp
  tags: wordpress

- name: Extract WordPress package
  unarchive:
    src: "/tmp/wordpress-{{ wordpress.version }}-ja.tar.gz"
    dest: /var/www
    copy: no
  become: yes
  tags: wordpress

- name: Generate secret key
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    return_content: yes
  register: secret_key
  tags: wordpress

- name: Generate wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: 0400
  become: yes
  tags: wordpress

- name: Install PHP extensions for WordPress
  apt:
    pkg:
      - "php{{ php.version }}-mysql"
  become: yes
  tags: wordpress
